In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("latency_metrics.csv")

In [3]:
df

                          timestamp messageType  latencyMs statusCode roomId
0       2025-10-10T19:25:00.820485Z       LEAVE        166    SUCCESS  room1
1       2025-10-10T19:25:01.867565Z        TEXT        139    SUCCESS  room4
2       2025-10-10T19:25:01.867625Z        JOIN        144    SUCCESS  room4
3       2025-10-10T19:25:01.867671Z        TEXT        144    SUCCESS  room4
4       2025-10-10T19:25:01.867717Z        TEXT        144    SUCCESS  room4
...                             ...         ...        ...        ...    ...
499996  2025-10-10T19:25:02.922113Z        TEXT      34648    SUCCESS  room9
499997  2025-10-10T19:25:02.922326Z        TEXT      34661    SUCCESS  room9
499998  2025-10-10T19:25:02.922358Z        TEXT      34661    SUCCESS  room9
499999  2025-10-10T19:25:02.923911Z        TEXT      34661    SUCCESS  room9
500000  2025-10-10T19:25:02.925982Z        TEXT      34717    SUCCESS  room9

[500001 rows x 5 columns]